sudo: required
# We use Groovy
language: groovy

jdk:
  - openjdk8

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - gradle clean build

script:
  - docker build -t bhoopendra/social-media-api .

after_success:
  - docker push bhoopendra/social-media-api
