# We use Groovy
language: groovy

jdk:
  - openjdk8

services:
  - docker

before_install:
  - gradle clean
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker pull "$DOCKER_ID"/alpine-java:latest

script:
  - gradle clean install
